from datetime import timedelta

from sqlalchemy import func, select
from sqlalchemy.orm import Session

from app.core.config import get_settings
from app.models.agent import Agent
from app.models.base import utcnow
from app.models.report import Report
from app.models.task import Task
from app.services.health_service import HealthService
from app.services.llm_service import LLMService
from app.services.runtime_config_service import RuntimeConfigService

settings = get_settings()


class ReportService:
    @staticmethod
    def generate_daily_report(db: Session) -> Report:
        period_end = utcnow()
        period_start = period_end - timedelta(days=1)

        task_counts = {
            getattr(status, "value", str(status)): count
            for status, count in db.execute(
                select(Task.status, func.count(Task.id))
                .where(Task.created_at >= period_start)
                .group_by(Task.status)
            ).all()
        }
        agent_counts = {
            getattr(status, "value", str(status)): count
            for status, count in db.execute(select(Agent.status, func.count(Agent.id)).group_by(Agent.status)).all()
        }

        content_lines = [
            f"Daily report window: {period_start.isoformat()} to {period_end.isoformat()}",
            "",
            "Task summary:",
            f"- pending: {task_counts.get('pending', 0)}",
            f"- in_progress: {task_counts.get('in_progress', 0)}",
            f"- completed: {task_counts.get('completed', 0)}",
            f"- failed: {task_counts.get('failed', 0)}",
            "",
            "Agent summary:",
            f"- online: {agent_counts.get('online', 0)}",
            f"- busy: {agent_counts.get('busy', 0)}",
            f"- offline: {agent_counts.get('offline', 0)}",
        ]
        llm_summary = ReportService._build_llm_summary(db, content_lines)
        if llm_summary:
            content_lines.extend(["", "AI summary:", llm_summary])

        report = Report(
            report_type="daily",
            title="Daily AI Ops Report",
            content="\n".join(content_lines),
            period_start=period_start,
            period_end=period_end,
            metadata_json={"task_counts": task_counts, "agent_counts": agent_counts},
        )
        db.add(report)
        db.commit()
        db.refresh(report)
        return report

    @staticmethod
    def capture_health_snapshot(db: Session) -> Report:
        snapshot = HealthService.snapshot()
        report = Report(
            report_type="health_check",
            title=f"Health Snapshot: {snapshot['status']}",
            content="\n".join(
                [
                    f"Overall: {snapshot['status']}",
                    f"Database: {snapshot['services']['database']}",
                    f"Redis: {snapshot['services']['redis']}",
                    f"Ollama: {snapshot['services']['ollama']}",
                ]
            ),
            metadata_json=snapshot,
        )
        db.add(report)
        db.commit()
        db.refresh(report)
        return report

    @staticmethod
    def _build_llm_summary(db: Session, content_lines: list[str]) -> str | None:
        active_llm = RuntimeConfigService.get_active_llm(db)
        prompt = [
            {
                "role": "system",
                "content": (
                    "You are generating a concise daily operations summary for a personal AI ops platform. "
                    "Write 4 to 6 short lines. Highlight important changes, risks, and what needs attention next."
                ),
            },
            {
                "role": "user",
                "content": "\n".join(content_lines),
            },
        ]
        try:
            summary, provider = LLMService.generate_reply(
                prompt,
                active_provider=active_llm["provider"],
                active_model=active_llm["model"],
            )
            return f"{summary}\n\nGenerated by: {provider}"
        except Exception:
            return None
