"""add_projects

Revision ID: 02553c1779ee
Revises: e0f91cf2aa82
Create Date: 2026-04-25 08:27:06.231803+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '02553c1779ee'
down_revision: Union[str, None] = 'e0f91cf2aa82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('repo_url', sa.String(length=500), nullable=True),
    sa.Column('default_branch', sa.String(length=120), nullable=False),
    sa.Column('branches', sa.JSON(), nullable=False),
    sa.Column('agent_name', sa.String(length=120), nullable=True),
    sa.Column('local_path', sa.String(length=500), nullable=True),
    sa.Column('vps_path', sa.String(length=500), nullable=True),
    sa.Column('deploy_command', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_agent_name'), 'projects', ['agent_name'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_index('ix_projects_user_slug', 'projects', ['user_id', 'slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_projects_user_slug', table_name='projects')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_agent_name'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
