"""initial_schema

Revision ID: 5dda5a254210
Revises: 
Create Date: 2026-04-24 11:04:33.391186+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5dda5a254210'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('online', 'busy', 'offline', name='agentstatus'), nullable=False),
    sa.Column('capabilities_json', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_task_id', sa.String(length=32), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_id'), 'agents', ['id'], unique=False)
    op.create_index(op.f('ix_agents_name'), 'agents', ['name'], unique=True)
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_settings_id'), 'app_settings', ['id'], unique=False)
    op.create_index(op.f('ix_app_settings_key'), 'app_settings', ['key'], unique=True)
    op.create_table('calendar_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=32), nullable=False),
    sa.Column('platform_user_id', sa.String(length=120), nullable=False),
    sa.Column('user_session_id', sa.String(length=120), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'cancelled', 'completed', name='calendareventstatus'), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('meeting_url', sa.String(length=500), nullable=True),
    sa.Column('attendees_json', sa.JSON(), nullable=False),
    sa.Column('reminder_minutes_before', sa.Integer(), nullable=False),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ics_path', sa.String(length=500), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_events_event_id'), 'calendar_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_calendar_events_id'), 'calendar_events', ['id'], unique=False)
    op.create_index(op.f('ix_calendar_events_platform_user_id'), 'calendar_events', ['platform_user_id'], unique=False)
    op.create_index(op.f('ix_calendar_events_starts_at'), 'calendar_events', ['starts_at'], unique=False)
    op.create_index(op.f('ix_calendar_events_status'), 'calendar_events', ['status'], unique=False)
    op.create_index(op.f('ix_calendar_events_user_session_id'), 'calendar_events', ['user_session_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=120), nullable=False),
    sa.Column('platform_user_id', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('role', sa.Enum('system', 'user', 'assistant', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_id'), 'conversation_messages', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_platform_user_id'), 'conversation_messages', ['platform_user_id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_session_id'), 'conversation_messages', ['session_id'], unique=False)
    op.create_table('device_commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('command_id', sa.String(length=32), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('command_type', sa.String(length=80), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='devicecommandstatus'), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('artifact_path', sa.String(length=500), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=120), nullable=True),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_commands_agent_name'), 'device_commands', ['agent_name'], unique=False)
    op.create_index(op.f('ix_device_commands_command_id'), 'device_commands', ['command_id'], unique=True)
    op.create_index(op.f('ix_device_commands_command_type'), 'device_commands', ['command_type'], unique=False)
    op.create_index(op.f('ix_device_commands_created_by_user_id'), 'device_commands', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_device_commands_id'), 'device_commands', ['id'], unique=False)
    op.create_index(op.f('ix_device_commands_status'), 'device_commands', ['status'], unique=False)
    op.create_table('finance_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.String(length=40), nullable=False),
    sa.Column('platform_user_id', sa.String(length=120), nullable=False),
    sa.Column('session_id', sa.String(length=120), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('merchant_name', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('currency', sa.String(length=12), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_method', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_entries_entry_id'), 'finance_entries', ['entry_id'], unique=True)
    op.create_index(op.f('ix_finance_entries_id'), 'finance_entries', ['id'], unique=False)
    op.create_index(op.f('ix_finance_entries_platform_user_id'), 'finance_entries', ['platform_user_id'], unique=False)
    op.create_index(op.f('ix_finance_entries_session_id'), 'finance_entries', ['session_id'], unique=False)
    op.create_table('finance_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(length=40), nullable=False),
    sa.Column('platform_user_id', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.Enum('category_keyword', 'threshold', name='financerulekind'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('criteria_json', sa.JSON(), nullable=False),
    sa.Column('action_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_rules_id'), 'finance_rules', ['id'], unique=False)
    op.create_index(op.f('ix_finance_rules_platform_user_id'), 'finance_rules', ['platform_user_id'], unique=False)
    op.create_index(op.f('ix_finance_rules_rule_id'), 'finance_rules', ['rule_id'], unique=True)
    op.create_table('memory_design',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('image_paths', sa.JSON(), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('project_key', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_design_id'), 'memory_design', ['id'], unique=False)
    op.create_index(op.f('ix_memory_design_name'), 'memory_design', ['name'], unique=False)
    op.create_index(op.f('ix_memory_design_project_key'), 'memory_design', ['project_key'], unique=False)
    op.create_index(op.f('ix_memory_design_user_id'), 'memory_design', ['user_id'], unique=False)
    op.create_index('ix_memory_design_user_name', 'memory_design', ['user_id', 'name'], unique=True)
    op.create_table('memory_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('tool', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('session_id', sa.String(length=120), nullable=True),
    sa.Column('project_key', sa.String(length=120), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_write_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_usage_created_at'), 'memory_usage', ['created_at'], unique=False)
    op.create_index(op.f('ix_memory_usage_id'), 'memory_usage', ['id'], unique=False)
    op.create_index(op.f('ix_memory_usage_model'), 'memory_usage', ['model'], unique=False)
    op.create_index(op.f('ix_memory_usage_project_key'), 'memory_usage', ['project_key'], unique=False)
    op.create_index(op.f('ix_memory_usage_session_id'), 'memory_usage', ['session_id'], unique=False)
    op.create_index(op.f('ix_memory_usage_tool'), 'memory_usage', ['tool'], unique=False)
    op.create_index('ix_memory_usage_user_created', 'memory_usage', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_memory_usage_user_id'), 'memory_usage', ['user_id'], unique=False)
    op.create_index('ix_memory_usage_user_tool', 'memory_usage', ['user_id', 'tool'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.String(length=32), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_report_id'), 'reports', ['report_id'], unique=True)
    op.create_index(op.f('ix_reports_report_type'), 'reports', ['report_type'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'failed', name='taskstatus'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('command_type', sa.String(length=50), nullable=True),
    sa.Column('assigned_agent_name', sa.String(length=100), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=120), nullable=True),
    sa.Column('user_session_id', sa.String(length=120), nullable=True),
    sa.Column('result_text', sa.Text(), nullable=True),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_assigned_agent_name'), 'tasks', ['assigned_agent_name'], unique=False)
    op.create_index(op.f('ix_tasks_created_by_user_id'), 'tasks', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_task_id'), 'tasks', ['task_id'], unique=True)
    op.create_index(op.f('ix_tasks_user_session_id'), 'tasks', ['user_session_id'], unique=False)
    op.create_table('uploaded_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.String(length=40), nullable=False),
    sa.Column('access_token', sa.String(length=40), nullable=False),
    sa.Column('platform_user_id', sa.String(length=120), nullable=False),
    sa.Column('session_id', sa.String(length=120), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.Enum('image', 'document', 'binary', name='uploadedassetkind'), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_assets_access_token'), 'uploaded_assets', ['access_token'], unique=False)
    op.create_index(op.f('ix_uploaded_assets_asset_id'), 'uploaded_assets', ['asset_id'], unique=True)
    op.create_index(op.f('ix_uploaded_assets_id'), 'uploaded_assets', ['id'], unique=False)
    op.create_index(op.f('ix_uploaded_assets_platform_user_id'), 'uploaded_assets', ['platform_user_id'], unique=False)
    op.create_index(op.f('ix_uploaded_assets_session_id'), 'uploaded_assets', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploaded_assets_session_id'), table_name='uploaded_assets')
    op.drop_index(op.f('ix_uploaded_assets_platform_user_id'), table_name='uploaded_assets')
    op.drop_index(op.f('ix_uploaded_assets_id'), table_name='uploaded_assets')
    op.drop_index(op.f('ix_uploaded_assets_asset_id'), table_name='uploaded_assets')
    op.drop_index(op.f('ix_uploaded_assets_access_token'), table_name='uploaded_assets')
    op.drop_table('uploaded_assets')
    op.drop_index(op.f('ix_tasks_user_session_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_task_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_by_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_agent_name'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_reports_report_type'), table_name='reports')
    op.drop_index(op.f('ix_reports_report_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index('ix_memory_usage_user_tool', table_name='memory_usage')
    op.drop_index(op.f('ix_memory_usage_user_id'), table_name='memory_usage')
    op.drop_index('ix_memory_usage_user_created', table_name='memory_usage')
    op.drop_index(op.f('ix_memory_usage_tool'), table_name='memory_usage')
    op.drop_index(op.f('ix_memory_usage_session_id'), table_name='memory_usage')
    op.drop_index(op.f('ix_memory_usage_project_key'), table_name='memory_usage')
    op.drop_index(op.f('ix_memory_usage_model'), table_name='memory_usage')
    op.drop_index(op.f('ix_memory_usage_id'), table_name='memory_usage')
    op.drop_index(op.f('ix_memory_usage_created_at'), table_name='memory_usage')
    op.drop_table('memory_usage')
    op.drop_index('ix_memory_design_user_name', table_name='memory_design')
    op.drop_index(op.f('ix_memory_design_user_id'), table_name='memory_design')
    op.drop_index(op.f('ix_memory_design_project_key'), table_name='memory_design')
    op.drop_index(op.f('ix_memory_design_name'), table_name='memory_design')
    op.drop_index(op.f('ix_memory_design_id'), table_name='memory_design')
    op.drop_table('memory_design')
    op.drop_index(op.f('ix_finance_rules_rule_id'), table_name='finance_rules')
    op.drop_index(op.f('ix_finance_rules_platform_user_id'), table_name='finance_rules')
    op.drop_index(op.f('ix_finance_rules_id'), table_name='finance_rules')
    op.drop_table('finance_rules')
    op.drop_index(op.f('ix_finance_entries_session_id'), table_name='finance_entries')
    op.drop_index(op.f('ix_finance_entries_platform_user_id'), table_name='finance_entries')
    op.drop_index(op.f('ix_finance_entries_id'), table_name='finance_entries')
    op.drop_index(op.f('ix_finance_entries_entry_id'), table_name='finance_entries')
    op.drop_table('finance_entries')
    op.drop_index(op.f('ix_device_commands_status'), table_name='device_commands')
    op.drop_index(op.f('ix_device_commands_id'), table_name='device_commands')
    op.drop_index(op.f('ix_device_commands_created_by_user_id'), table_name='device_commands')
    op.drop_index(op.f('ix_device_commands_command_type'), table_name='device_commands')
    op.drop_index(op.f('ix_device_commands_command_id'), table_name='device_commands')
    op.drop_index(op.f('ix_device_commands_agent_name'), table_name='device_commands')
    op.drop_table('device_commands')
    op.drop_index(op.f('ix_conversation_messages_session_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_platform_user_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_calendar_events_user_session_id'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_status'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_starts_at'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_platform_user_id'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_id'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_event_id'), table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_index(op.f('ix_app_settings_key'), table_name='app_settings')
    op.drop_index(op.f('ix_app_settings_id'), table_name='app_settings')
    op.drop_table('app_settings')
    op.drop_index(op.f('ix_agents_name'), table_name='agents')
    op.drop_index(op.f('ix_agents_id'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
