"""add_routing_decisions

Revision ID: bb999d88703e
Revises: 02553c1779ee
Create Date: 2026-04-25 08:41:02.953441+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bb999d88703e'
down_revision: Union[str, None] = '02553c1779ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routing_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('dispatched', sa.Boolean(), nullable=False),
    sa.Column('dispatch_action', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routing_decisions_category'), 'routing_decisions', ['category'], unique=False)
    op.create_index(op.f('ix_routing_decisions_id'), 'routing_decisions', ['id'], unique=False)
    op.create_index(op.f('ix_routing_decisions_source'), 'routing_decisions', ['source'], unique=False)
    op.create_index('ix_routing_decisions_user_created', 'routing_decisions', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_routing_decisions_user_id'), 'routing_decisions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routing_decisions_user_id'), table_name='routing_decisions')
    op.drop_index('ix_routing_decisions_user_created', table_name='routing_decisions')
    op.drop_index(op.f('ix_routing_decisions_source'), table_name='routing_decisions')
    op.drop_index(op.f('ix_routing_decisions_id'), table_name='routing_decisions')
    op.drop_index(op.f('ix_routing_decisions_category'), table_name='routing_decisions')
    op.drop_table('routing_decisions')
    # ### end Alembic commands ###
