"""add_pending_approvals

Revision ID: e0f91cf2aa82
Revises: 5dda5a254210
Create Date: 2026-04-24 11:34:54.087255+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e0f91cf2aa82'
down_revision: Union[str, None] = '5dda5a254210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('approval_id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=120), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('session_id', sa.String(length=120), nullable=True),
    sa.Column('tool_name', sa.String(length=120), nullable=False),
    sa.Column('action_summary', sa.Text(), nullable=False),
    sa.Column('action_detail', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.String(length=120), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=60), nullable=True),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_approvals_approval_id'), 'pending_approvals', ['approval_id'], unique=True)
    op.create_index(op.f('ix_pending_approvals_id'), 'pending_approvals', ['id'], unique=False)
    op.create_index(op.f('ix_pending_approvals_session_id'), 'pending_approvals', ['session_id'], unique=False)
    op.create_index(op.f('ix_pending_approvals_status'), 'pending_approvals', ['status'], unique=False)
    op.create_index(op.f('ix_pending_approvals_user_id'), 'pending_approvals', ['user_id'], unique=False)
    op.create_index('ix_pending_approvals_user_status', 'pending_approvals', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pending_approvals_user_status', table_name='pending_approvals')
    op.drop_index(op.f('ix_pending_approvals_user_id'), table_name='pending_approvals')
    op.drop_index(op.f('ix_pending_approvals_status'), table_name='pending_approvals')
    op.drop_index(op.f('ix_pending_approvals_session_id'), table_name='pending_approvals')
    op.drop_index(op.f('ix_pending_approvals_id'), table_name='pending_approvals')
    op.drop_index(op.f('ix_pending_approvals_approval_id'), table_name='pending_approvals')
    op.drop_table('pending_approvals')
    # ### end Alembic commands ###
